export const _SUCCESS_SUFIX = '_SUCCESS';
export const _ERROR_SUFIX = '_ERROR';


// board
export default {
  ADD_ISSUE: 'ADD_ISSUE',

  UPDATE_ISSUE: 'UPDATE_ISSUE',
  [`UPDATE_ISSUE${_SUCCESS_SUFIX}`]: `UPDATE_ISSUE${_SUCCESS_SUFIX}`,
  [`UPDATE_ISSUE${_ERROR_SUFIX}`]: `UPDATE_ISSUE${_ERROR_SUFIX}`,

  DELETE_ISSUE: 'DELETE_ISSUE',
  [`DELETE_ISSUE${_SUCCESS_SUFIX}`]: `DELETE_ISSUE${_SUCCESS_SUFIX}`,
  [`DELETE_ISSUE${_ERROR_SUFIX}`]: `DELETE_ISSUE${_ERROR_SUFIX}`,

  GET_ISSUES: 'GET_ISSUES',
  [`GET_ISSUES${_SUCCESS_SUFIX}`]: `GET_ISSUES${_SUCCESS_SUFIX}`,
  [`GET_ISSUES${_ERROR_SUFIX}`]: `GET_ISSUES${_ERROR_SUFIX}`,

  SET_ISSUE_FORM_ELEMENT: 'SET_FORM_ELEMENT',
  SUMBIT_ISSUE_FORM: 'SUMBIT_ISSUE_FORM',
  [`SUMBIT_ISSUE_FORM${_SUCCESS_SUFIX}`]: `SUMBIT_ISSUE_FORM${_SUCCESS_SUFIX}`,
  [`SUMBIT_ISSUE_FORM${_ERROR_SUFIX}`]: `SUMBIT_ISSUE_FORM${_ERROR_SUFIX}`,
  TOGGLE_ISSUE_FORM: 'TOGGLE_ISSUE_FORM',

};
