export const ACTION_TYPE_SUFIX = {
  ERROR: '_ERROR',
  SUCCESS: '_SUCCESS',
} as const;

type ActionTypeSufixKeys = keyof typeof ACTION_TYPE_SUFIX;
export type ActionTypeSufix = typeof ACTION_TYPE_SUFIX[ActionTypeSufixKeys];

export const ACTION_TYPE = {
  ADD_ISSUE: 'ADD_ISSUE',

  UPDATE_ISSUE: 'UPDATE_ISSUE',
  [`UPDATE_ISSUE${ACTION_TYPE_SUFIX.SUCCESS}`]: `UPDATE_ISSUE${ACTION_TYPE_SUFIX.SUCCESS}`,
  [`UPDATE_ISSUE${ACTION_TYPE_SUFIX.ERROR}`]: `UPDATE_ISSUE${ACTION_TYPE_SUFIX.ERROR}`,

  DELETE_ISSUE: 'DELETE_ISSUE',
  [`DELETE_ISSUE${ACTION_TYPE_SUFIX.SUCCESS}`]: `DELETE_ISSUE${ACTION_TYPE_SUFIX.SUCCESS}`,
  [`DELETE_ISSUE${ACTION_TYPE_SUFIX.ERROR}`]: `DELETE_ISSUE${ACTION_TYPE_SUFIX.ERROR}`,

  GET_ISSUES: 'GET_ISSUES',
  [`GET_ISSUES${ACTION_TYPE_SUFIX.SUCCESS}`]: `GET_ISSUES${ACTION_TYPE_SUFIX.SUCCESS}`,
  [`GET_ISSUES${ACTION_TYPE_SUFIX.ERROR}`]: `GET_ISSUES${ACTION_TYPE_SUFIX.ERROR}`,

  SET_ISSUE_FORM_ELEMENT: 'SET_FORM_ELEMENT',
  SUMBIT_ISSUE_FORM: 'SUMBIT_ISSUE_FORM',
  [`SUMBIT_ISSUE_FORM${ACTION_TYPE_SUFIX.SUCCESS}`]: `SUMBIT_ISSUE_FORM${ACTION_TYPE_SUFIX.SUCCESS}`,
  [`SUMBIT_ISSUE_FORM${ACTION_TYPE_SUFIX.ERROR}`]: `SUMBIT_ISSUE_FORM${ACTION_TYPE_SUFIX.ERROR}`,
  TOGGLE_ISSUE_FORM: 'TOGGLE_ISSUE_FORM',
} as const;

type ActionTypeKeys = keyof typeof ACTION_TYPE;
export type ActionType = typeof ACTION_TYPE[ActionTypeKeys];
